---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ing-route
  namespace: ip812
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.ip812.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
