---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ip812
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: "^34.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ip812
  interval: 10m
  install:
    createNamespace: true
  values:
    additionalArguments:
      - "--api.insecure=true"
      - "--providers.kubernetescrd"
      - "--providers.kubernetesingress"

    log:
      level: INFO

    ports:
      web:
        port: 80
        exposedPort: 80
        protocol: TCP

    ingressRoute:
      dashboard:
        enabled: true

    service:
      enabled: true
      type: LoadBalancer

    experimental:
      plugins:
        cloudflarewarp:
          moduleName: "github.com/BetterCorp/cloudflarewarp"
          version: "v1.3.0"

    http:
      routers:
        traefik:
          entryPoints:
            - web
      middlewares:
        cloudflarewarp:
          plugin:
            cloudflarewarp:
              disableDefault: false
              trustip:
                - "2400:cb00::/32"
