---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ing-route
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.ip812.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
