---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rbac-proxy
  namespace: experiment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-rbac-proxy
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rbac-proxy
subjects:
- kind: ServiceAccount
  name: kube-rbac-proxy
  namespace: experiment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: experiment
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        logs/0:
          receivers: [otlp]
          exporters: [debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-receiver
  namespace: experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-receiver
  template:
    metadata:
      labels:
        app: otel-receiver
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      shareProcessNamespace: true
      serviceAccountName: kube-rbac-proxy
      initContainers:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.22.1
        args:
        - "--logtostderr=true"
        - "--v=6"
        - "--secure-listen-address=[::]:8443"
        - "--upstream=http://127.0.0.1:4317/"
        # The OTLP exporter uses gRPC, which operates over HTTP/2. To support HTTP/2 over cleartext (h2c),
        # we must explicitly enable h2c in kube-rbac-proxy. By default, kube-rbac-proxy enforces HTTP/2 over TLS
        # as per the HTTP/2 specification. However, since kube-rbac-proxy forwards to the otel-collector over an unencrypted channel,
        # h2c support must be enforced when connecting to the upstream.
        - "--upstream-force-h2c"
        - "--tls-cert-file=/tls/tls.crt"
        - "--tls-private-key-file=/tls/tls.key"
        - "--kube-api-qps=1"
        - "--kube-api-burst=1"
        ports:
        - containerPort: 8443
          name: https
        restartPolicy: Always
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        args:
          - "--config=/etc/otelcol/config.yaml"
        ports:
          - name: otlp-grpc
            containerPort: 4317
        volumeMounts:
          - name: otel-config
            mountPath: /etc/otelcol
      - name: dlv
        image: golang:1.26.5
        command:
        - /bin/sh
        - -c
        - |
          go install github.com/go-delve/delve/cmd/dlv@latest
          until _PID="$(pgrep kube-rbac-proxy)"; do sleep 1; done
          exec dlv attach "${_PID}" --headless --listen=:2345 --api-version=2 --accept-multiclient --continue
        ports:
        - containerPort: 2345
          name: dlv
        securityContext:
          capabilities:
            add: ["SYS_PTRACE"]
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
        - name: tls
          secret:
            secretName: otel-receiver-tls
---
apiVersion: v1
kind: Service
metadata:
  name: otel-receiver
  namespace: experiment
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: otel-receiver
