---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: vault-auth
  namespace: vault
spec:
  organizationID: "some-id"
  projectID: "some-id"
  servicePrincipal:
    secretRef: hcp-credentials
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vault-secrets-app
  namespace: vault
spec:
  appName: prod
  destination:
    name: vault-secrets-app
    create: true
    overwrite: true
  hcpAuthRef: vault/vault-auth
  refreshAfter: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-display-envs
  namespace: vault
  labels:
    app: debug-display-envs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-display-envs
  template:
    metadata:
      labels:
        app: debug-display-envs
    spec:
      containers:
        - name: debug-display-envs
          image: iypetrov/debug-display-envs:1.1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: vault-secrets-app
                  key: pg_endpoint
