---
apiVersion: v1
kind: Service
metadata:
  name: clickstack-otel-collector-lb
  namespace: clickstack
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: clickstack
    app.kubernetes.io/name: otel-collector
    component: standalone-collector
  ports:
  - name: health-check
    port: 13133
    protocol: TCP
    targetPort: 13133
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  - appProtocol: grpc
    name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
