---
apiVersion: v1
kind: Service
metadata:
  name: clickstack-app-node-port
  namespace: clickstack
spec:
  type: NodePort
  selector:
    app: clickstack
    app.kubernetes.io/instance: clickstack
    app.kubernetes.io/name: clickstack
  ports:
  - name: app
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
