---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vault-secrets-app
  namespace: ip812
spec:
  appName: prod
  hcpAuthRef: ip812/vault-auth
  refreshAfter: 30s
  destination:
    name: vault-secrets-app
    create: true
    overwrite: true
    transformation:
     templates:
       slk:
         name: slk
         text: '{{- get .Secrets "slk_bot_token" -}}'
