---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-template
  namespace: services-explore
data:
  default.conf.template: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            default_type text/html;
            return 200 "<html><body><h1>Pod Name: ${POD_NAME}</h1><p>Pod IP: ${POD_IP}</p></body></html>";
        }
    }

