---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-better
  namespace: services-explore
  labels:
    app: foo-better
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo-better
  template:
    metadata:
      labels:
        app: foo-better
    spec:
      containers:
        - name: foo 
          image: iypetrov/debug-display-envs:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true

