---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
  namespace: services-explore
spec:
  type: NodePort
  selector:
    app: foo-better
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

