---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: services-explore
spec:
  selector:
    app: nginx-better
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

