---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: ip812
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.2.1
          args:
            - "tunnel"
            - "run"
            - "--protocol"
            - "http2"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secrets-app
                  key: cf_tunnel_token
          livenessProbe:
            httpGet:
              path: /ready
              port: 20241
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
