---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: debug-display-req-headers-img-update-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux.bot@gmail.com
        name: flux.bot
      messageTemplate: "Update {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main
  update:
    strategy: Setters
