---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logger
  name: logger
spec:
  containers:
    - image: nginx:alpine
      name: pod
      volumeMounts:
        - mountPath: /var/www/nginx
          name: foo
  volumes:
    - name: foo
      persistentVolumeClaim: 
        claimName: log-claim