---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-deployment
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-deployment-auto-instrumentation
  namespace: demo-deployment
spec:
  exporter:
    endpoint: http://auto-instrumentation-receiver-collector.receiver.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-deployment
  labels:
    app: demo-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-go-deployment
  template:
    metadata:
      labels:
        app: demo-go-deployment
      annotations:
        instrumentation.opentelemetry.io/inject-go: 'true'
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/usr/bin/minio'
    spec:
      containers:
      - image: minio/minio
        name: minio
        args: ["server", "/data"]
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        securityContext:
          privileged: true
          runAsUser: 0
