bootstrap:
	flux bootstrap github \
		--token-auth=true \
		--owner=iypetrov \
		--repository=k8s-playground \
		--branch=main \
		--path=fluxcd-intro \
		--read-write-key=true \
		--personal=false \
		--author-email=bot.fluxcd@gmail.com \
		--author-name="FluxCD [BOT]" \	
		--components-extra=image-automation-controller,image-reflector-controller
