---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vault-secrets-app
  namespace: vault
spec:
  appName: prod
  destination:
    name: vault-secrets-app
    create: true
    overwrite: true
  hcpAuthRef: vault/vault-auth
  refreshAfter: 30s
