---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.2.1
          args:
            - "tunnel"
            - "run"
            - "--protocol"
            - "http2"
          env:
            - name: TUNNEL_TOKEN
              value: "TUNNEL_TOKEN"
          livenessProbe:
            httpGet:
              path: /ready
              port: 20241
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
