---
apiVersion: v1
kind: Namespace
metadata:
  name: debug-display-req-headers
---
apiVersion: v1
kind: Service
metadata:
  name: debug-display-req-headers-svc
  namespace: debug-display-req-headers
spec:
  type: ClusterIP
  selector:
    app: debug-display-req-headers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-display-req-headers
  namespace: debug-display-req-headers
  labels:
    app: debug-display-req-headers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-display-req-headers
  template:
    metadata:
      labels:
        app: debug-display-req-headers
    spec:
      containers:
        - name: debug-display-envs
          image: iypetrov/debug-display-req-headers:1.2.0
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: debug-display-req-headers-ing
  namespace: debug-display-req-headers
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`template.ip812.com`)
      kind: Rule
      services:
        - name: debug-display-req-headers-svc
          port: 80
